[package]
name = "exprtree"
version = "0.1.0"
authors = ["Maxim Bogdanov <maxim.bogdanov@coins.ph>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
num = "0.3"
arrow = "4.0.0"
datafusion = { git = "https://github.com/apache/arrow-datafusion" }
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
criterion = "0.3"
async-trait = "0.1.41"
futures = "0.3"
enum_dispatch = "0.3.7"
[[bench]]
name = "count"
harness = false