[package]
name = "store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "6.3.0"
chrono = { version = "0.4.19", features = ["serde"] }
datafusion = "6.0.0"