[package]
name = "query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
datafusion = "6.0.0"
arrow = "5.2.0"
optiprism = {path = "../optiprism" }
store = {path = "../store" }
mockall = "0.10.1"