[package]
name = "query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metadata = { path = "../metadata" }
chrono = "0.4"
datafusion = "6.0.0"
arrow = { version = "6.1.0", features = ["prettyprint"] }
platform = { path = "../platform" }
store = { path = "../store" }
mockall = "0.10.1"
tokio = { version = "1.10.1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
] }
rocksdb = { version = "0.17.0", features = ["multi-threaded-cf"] }
futures = "0.3"
bincode = "1.3.3"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"